sorentwo/braintree-elixir

lib/client_token.ex, test/integration/client_token_test.exs
Implements a `generate` method comparable to the [Ruby SDK](https://developers.braintreepayments.com/reference/request/client-token/generate/ruby) for creating new client tokens. A client token is required to initialize a client SDK.
=> Add client token module for generating new client tokens

lib/transaction.ex, test/integration/transaction_test.exs
Adds support for making settlements at a later time, if the option for settlement was false while creating the charge.
=> add submit_for_settlement/2 method

lib/customer.ex, test/customer_test.exs
The response payload includes `paypal_accounts` -- this PR runs them through the `PaypalAccount.construct` function.
=> Construct the Paypal Account structs too

mix.exs
this adds `xmerl` to the applications list. without it, xmerl is missing in (exrm-)releases.
=> add xmerl to applications list

README.md, lib/http.ex
While Braintree is generally fast for credit card processing, the PayPal sandbox is often slower than the [relatively] low HTTPoison defaults.  This adds the ability to override (or keep) the timeout parameters.
=> Add Configurable HTTPoison Timeouts

lib/plan.ex, test/integration/plan_test.exs, test/plan_test.exs
Now that plans come through properly from the API here is support for `Plan.all`
I haven't added integration tests yet. As far as I can tell you're testing against your own sandbox? Either you could let me know what data you have in the sandbox for plans, or if you'd like to add some tests for this then that'd be welcome.
Hope this helps :)
=> Add Plan.all support

lib/braintree.ex, lib/http.ex, test/http_test.exs
It's a pretty common patten for configuring API keys, and makes using the library in releases much easier.
=> Support {:system, VAR} for configs

lib/xml/decoder.ex, lib/xml/entity.ex, priv/entities.txt
I removed entities that should not be decoded before xmerl parses the document, as doing so, would produce invalid XML.
This should solve for #23
=> This patch correctly handles &amp; in the Braintree response XML

lib/transaction.ex
Because Sting != String...and it was blowing up dialyxer.
Fixed the typo.
=> Fix typo in in typespec

README.md
Fix a typo in the readme
replace "ot" with "to"
=> fix typo s/ ot / to /

lib/http.ex
Thank you very much @sorentwo for your very fast PR-merge and new release, I'm already using it in my application 👍.
One small PR this time about reverting from `Keyword.get` to classical `||` operator. This is because the default clause of the `Keyword.get` function will always be evaluated... This lead to an exception if the config keys are not set at all...
Thanks.
=> Use Keyword.get_lazy instead of Keyword.get

lib/add_on.ex, lib/address.ex, lib/braintree.ex, lib/client_token.ex, lib/construction.ex, lib/credit_card.ex, lib/credit_card_verification.ex, lib/customer.ex, lib/error_response.ex, lib/http.ex, lib/merchant/account.ex, lib/payment_method.ex, lib/payment_method_nonce.ex, lib/paypal_account.ex, lib/plan.ex, lib/search.ex, lib/settlement_batch_summary.ex, lib/subscription.ex, lib/transaction.ex, lib/util.ex, lib/xml/decoder.ex, lib/xml/encoder.ex, mix.exs, mix.lock
I was trying to use dialyzer in a project of mine using this library and noticed errors that I couldn't fix without touching this library.  Here are some fixes I think will help, but there's plenty of room for other improvements.  At least I think this is a good start.
The main issues:
* `Map.t` doesn't exist, it should just be `map`
* `[]` I think matches only "empty list". `[any]` is a generic "list of zero or more anything"
* The exception stuff was a bit squirrelly, I opted to just treat it like a behavior implementation
* Because `new/1` was being defined in `Braintree.Construction`, I removed the typespecs for all the overridden ones, because dialyzer can't handle more than one typespec per function
Hope this helps, let me know if you'd like anything changed! ;)
=> Add dialyxir and fix all the typespecs

lib/transaction_line_item.ex, test/integration/transaction_line_item_test.exs
This creates the `TransactionLineItem` module and implements the `find_all/1` action as documented here: https://developers.braintreepayments.com/reference/response/transaction-line-item/ruby
Tried to mostly stick with the style of the codebase :p.
=> Feature - Add TransactionLineItem.find_all/1

lib/http.ex
@sorentwo I haven't had a chance to really look into this one, but I've seen this error in our app a few times:
```
HTTP request error: no case clause matching: {:error, :connect_timeout}
...
(braintree) lib/client_token.ex:35: Braintree.ClientToken.generate/1
```
Looks like we include 504 status code [here](https://github.com/sorentwo/braintree-elixir/blob/master/lib/http.ex#L96) but do not have a `code_to_reason` mapping.
If this doesn't make sense I can dig a bit more. Thanks!
=> Add mapping for Gateway timeout

lib/search.ex
The `Search` module was not working for transactions. After some research I found out that `transactions` behave the same way as `verifications`, so I've extended the `fetch_records_chunk/4` function to work for transactions.
Before this line was blowing up:
```elixir
{:ok, transactions} = Braintree.Search.perform(%{ids: ["some-id-1", "some-id-2"]}, "transactions", &Braintree.Transaction.new/1)
```
and now it returns the results as intended.
=> Patch `Search.perform` to also work on transactions

README.md, lib/http.ex
I would like to be able to use [`Bypass`](https://github.com/PSPDFKit-labs/bypass) to test code that calls out to `Braintree`. Because the endpoints are hardcoded, this is not possible without modifying the library. I would prefer to not be using a fork of the library though, so this PR would solve that. 
All in all, this PR does the following:
* Allows sandbox endpoint configuration of `:braintree` with config key `:sandbox_endpoint` which uses `@sandbox_endpoint` if no config is provided
* Moves production endpoint definition to attribute `@production_endpoint`
* Builds keyword list at runtime to prevent stale config
* Updates `README.md` to inform library users of new config option
=> Allow configuration of sandbox endpoint for testing

lib/android_pay_card.ex, lib/customer.ex, lib/payment_method.ex, test/customer_test.exs, test/integration/payment_method_test.exs
We have integrated with Google Ordering and customers pay with Google Pay. This PR adds support for this payment type.
=> Add support for android pay card

lib/webhook.ex, lib/webhook/digest.ex, lib/webhook/validation.ex, mix.exs, test/support/webhook_test_helper.ex, test/webhook/digest_test.exs, test/webhook/validation_test.exs, test/webhook_test.exs
- Ensure compatiblity with pre-OTP-22 version as well as OTP-22+
- Right now, Braintree.Webhook#parse/2 returns the signature and decoded
payload (an xml document embedded in a string) from Braintree for later post-processing
- Future work envision handling the webhook notification payload parsing
in a more standardized way
- Related to https://github.com/sorentwo/braintree-elixir/issues/98
=> Add module for parsing and validating webhook events from Braintree

lib/webhook/validation.ex
Related issue: https://github.com/sorentwo/braintree-elixir/issues/118
Change non-existing Braintree.fetch_env! to Braintree.get_env.
Braintree.get_env/1 throw error when searched env is not found, so its behavior should match the original code's intention
=> Change Braintree.fetch_env! to Braintree.get_env on Braintree.Webhook.Validation

lib/customer.ex, lib/payment_method.ex, lib/us_bank_account.ex
Some time ago I needed to support the ACH Direct Debit payment method
https://developer.paypal.com/braintree/docs/guides/ach/server-side
https://developer.paypal.com/braintree/docs/reference/response/us-bank-account/ruby
I'd be glad to add `UsBankAccount` struct to the master repo, in case someone would need this too
appreciate for review! thanks!
=> Support ACH Direct Debit payment methods

lib/http.ex
This typespec error isn't caught given the current dialyzer settings but will cause issues for clients expecting things like `{:error, :not_found}` which yield dialyzer warnings because it will trust the exported type here. There are some other improvements that can be made if you turn on `:underspecs` but it depends on how precise you want your specs to be.
=> Fix error type in HTTP response type specification

lib/http.ex, lib/plan.ex, test/integration/plan_test.exs
Added the find, update, and create functions under `Braintree.Plan` to access more of the Plan API.
Edit: Also added delete function
=> Adds more plan functionality

lib/webhook.ex, lib/webhook/validation.ex
I added a way to pass options to the webhook parser/validator, similar to other API functions.
=> allow passing options to webhook parser

lib/customer.ex
Fix for Dialyzer error related to missing `{:error, :not_found}` response type for `Customer.find/2`
=> Update Customer.find/2 typespec

lib/client_token.ex, lib/http.ex, test/client_token_test.exs, test/http_test.exs, test/support/config_helper.ex
I discovered  that the typespec on `Braintree.ClientToken.generate/2` defines it's error tuple as `{:error, ErrorResponse.t()`. However that is only returned when the API responds with `422`. In a project I used this for I had to add a dialyzer ignore entry to avoid an error. 
This updates the typespec to match what the `HTTP` module returns.
=> Fix typespec on ClientToken.generate/2

lib/add_on.ex, lib/address.ex, lib/client_token.ex, lib/customer.ex, lib/discount.ex, lib/merchant/account.ex, lib/payment_method.ex, lib/payment_method_nonce.ex, lib/paypal_account.ex, lib/plan.ex, lib/search.ex, lib/settlement_batch_summary.ex, lib/subscription.ex, lib/transaction.ex, lib/transaction_line_item.ex
After my last PR I realized that specs for all functions that return an error from the HTTP module have the same issue as `Braintree.ClientToken`. This update them so that in one's app you can do something like below without a dialyzer error.
This also fixes the typespec for `Transaction.amount` since it returns a string, not an int or float.
```elixir
case Braintree.Customer.find("ima-cool-user") do
{:ok, _customer} = response ->
response
{:error, :not_found} -> 
{:error, :not_found}
{:error, reason} = error ->
Logger.error("Braintree.Customer.find/2 Error: #{inspect(reason)}")
error
end
```
TL;DR - It fixes this for all modules that return the HTTP error.
```
The pattern can never match the type.
Pattern:
{:error, :not_found}
Type:
{:error,
%Braintree.ErrorResponse{
:errors => map(), …
```
=> Fix specs for functions returning HTTP errors

lib/http.ex, test/http_test.exs
Braintree experienced an outtage over the weekend and we received 502 errors. The library doesn't support that so `HTTP.code_to_reason/1` raised a FunctionClauseError `no function clause matching in Braintree.HTTP.code_to_reason/1`
=> [PATCH] Support common 5XX http statuses

test/http_test.exs, test/xml/encoder_test.exs
I noticed that some XML tests are failing sometimes. Iterating on maps doesn't guarantee order so the generated XML nodes aren't always in the same order. This updates those tests to assert the XML is generated as expected but node order won't cause a test failure.
=> [DEV] Update XML tests to eliminate false failures
